### ISSUE TITLE
Can't execute a proposals that are made in DAI as opposed to native tokens... something wrong in the conversion

### ISSUE THREAD

**Issue by GriffGreen** [1Hive/gardens#296] opened 2021-08-18 14:32 UTC
Not sure whats wrong with this proposal, what is keeping it from executing...

Link to proposal: https://gardens-rinkeby.1hive.org/#/garden/0x38c2c0b72b86858c04352356650ab8cec61d5fc9/proposal/9

<img width="922" alt="Screen Shot 2021-08-18 at 4 22 48 PM" src="https://user-images.githubusercontent.com/14945613/129916855-feb436d0-fff5-4dd4-8380-a5a28534e33b.png">

The likely issue is that it's asking for 100 Dai but that equates to 0 GIV? Thats bad.

I assume thats the reason why it won't execute but who know.. there might be other issues...

Here is the tx link that is failing: https://rinkeby.etherscan.io/tx/0x2ddc174319eba794bc660f4db8e6079a22cc244fa9637d06b7db4138337d2fbc

We just want to send you Snack... help us out :-D

**Comment by laurenluz** [comment] 2021-08-18 20:31
yeah the tx fails for me every time too... even though I'm the proposal creator. I also can't "change support" at this point and take back my tokens

**Comment by DonnaOftadeh** [comment] 2021-08-19 14:36
I also clicked on execute, nothing happened it didn't give any error.

**Comment by 0xGabi** [comment] 2021-08-24 16:29
Will suggest is likely related to the price oracle not been updated.

**Comment by willjgriff** [comment] 2021-08-25 13:21
A transaction link would be useful if you have one.

**Comment by willjgriff** [comment] 2021-08-25 13:34
For this to work there needs to be an wxdai/giv pair on the Rinkeby Uniswap with liquidity and the price oracle deployed for this Garden needs to be called consistently every 3 hours for 24 hours. The pair's liquidity is up to the relevant community to manage, the service that needs to be run for calling the price oracle consistently can be found here: https://github.com/1Hive/price-oracle-service

**Comment by 0xGabi** [comment] 2021-09-07 05:50
We can close this one, as it's not a bug. But instead an issue of better UX that we will tackle with the above new issue.

**Closed by 0xGabi** 2021-09-07 05:50 UTC
Labels: Bug 👩‍✈️, UX 💅
